spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      use-new-id-generator-mappings: 'true'
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    show-sql: 'true'
  profiles:
    active: { profile }
  redis:
    host: localhost
    port: 6379


